// Builds supabase/seed.sql from data/catalog.json so the database and the local catalog never drift.
// Run with: npm run seed:generate
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const { products } = JSON.parse(await readFile(path.join(root, "data/catalog.json"), "utf8"));

const q = (value) => (value === null || value === undefined ? "null" : `'${String(value).replaceAll("'", "''")}'`);

const rows = products.map((p, index) => {
  // Stagger created_at so "newest" sorting is stable and meaningful.
  const createdAt = new Date(Date.UTC(2026, 8, 1) - index * 86_400_000).toISOString();
  return `  (${q(p.id)}, ${q(p.name)}, ${q(p.slug)}, ${q(p.description)}, ${p.price}, ${q(p.images[0]?.src)}, ${q(
    JSON.stringify(p.images),
  )}::jsonb, ${q(p.category)}, ${p.stock}, ${p.featured}, ${q(p.badge)}, ${q(createdAt)})`;
});

const sql = `-- GENERATED by scripts/generate-seed.mjs from data/catalog.json. Do not edit by hand.
-- Safe to re-run: products are updated in place and orders keep their snapshots.
-- Note: re-running resets stock to the catalog values.

insert into public.products (id, name, slug, description, price, image_url, images, category, stock, featured, badge, created_at)
values
${rows.join(",\n")}
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  image_url = excluded.image_url,
  images = excluded.images,
  category = excluded.category,
  stock = excluded.stock,
  featured = excluded.featured,
  badge = excluded.badge;
`;

await writeFile(path.join(root, "supabase/seed.sql"), sql);
console.log(`Wrote supabase/seed.sql with ${products.length} products.`);
